apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otp-service

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - monitoring.yaml

commonLabels:
  app: otp-service

images:
  - name: otp-service
    newName: otp-service
    newTag: latest
